### Import libraries

In [6]:
import pandas as pd 
import yfinance as yf

### Download data

In [2]:
df = yf.download("AAPL",
                 start="2011-01-01",
                 end="2021-12-31",
                 progress=False)

### Inspect the downloaded data

In [3]:
print(f"Downloaded {len(df)} rows of data.")
df

Downloaded 2768 rows of data.

Price            Close        High         Low        Open     Volume
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
2011-01-03    9.874907    9.895582    9.733183    9.757153  445138400
2011-01-04    9.926446    9.962701    9.832362    9.960903  309080800
2011-01-05   10.007644   10.017831    9.872810    9.874309  255519600
2011-01-06    9.999555   10.045098    9.974685   10.029217  300428800
2011-01-07   10.071166   10.078057    9.944722   10.007345  311931200
...                ...         ...         ...         ...        ...
2021-12-23  172.496643  173.054417  171.508325  172.075879   68356600
2021-12-27  176.459732  176.547797  173.269704  173.289264   74919600
2021-12-28  175.442047  177.438273  174.698364  176.293385   79144300
2021-12-29  175.530090  176.753262  174.316698  175.481160   62348900
2021-12-30  174.375443  176.694587  174.267803  175.618190   59773000

[2768 rows x 5 columns]

### Additionally

#### Alternative way of download yfiance data

In [4]:
aapl_data = yf.Ticker("AAPL")

#### Showing data history

In [5]:
aapl_data.history()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-02-19 00:00:00-05:00,262.600006,264.480011,260.049988,260.579987,30845300,0.0,0.0
2026-02-20 00:00:00-05:00,258.970001,264.750000,258.160004,264.579987,42070500,0.0,0.0
2026-02-23 00:00:00-05:00,263.489990,269.429993,263.380005,266.179993,37308200,0.0,0.0
2026-02-24 00:00:00-05:00,267.859985,274.890015,267.709991,272.140015,47014600,0.0,0.0
2026-02-25 00:00:00-05:00,271.779999,274.940002,271.049988,274.230011,33714300,0.0,0.0
2026-02-26 00:00:00-05:00,274.950012,276.109985,270.799988,272.950012,32345100,0.0,0.0
2026-02-27 00:00:00-05:00,272.809998,272.809998,262.890015,264.179993,72366500,0.0,0.0
2026-03-02 00:00:00-05:00,262.410004,266.529999,260.200012,264.720001,41827900,0.0,0.0
2026-03-03 00:00:00-05:00,263.480011,265.559998,260.130005,263.750000,38568900,0.0,0.0
2026-03-04 00:00:00-05:00,264.649994,266.149994,261.420013,262.519989,39803100,0.0,0.0
2026-03-05 00:00:00-05:00,260.790009,261.559998,257.250000,260.290009,49658600,0.0,0.0
2026-03-06 00:00:00-05:00,258.630005,258.769989,254.369995,257.459991,41120000,0.0,0.0
2026-03-09 00:00:00-04:00,255.690002,261.149994,253.679993,259.880005,38218500,0.0,0.0
2026-03-10 00:00:00-04:00,257.649994,262.480011,256.950012,260.829987,30590800,0.0,0.0
2026-03-11 00:00:00-04:00,261.089996,262.130005,259.549988,260.809998,26218900,0.0,0.0
2026-03-12 00:00:00-04:00,258.660004,258.950012,254.179993,255.759995,40794000,0.0,0.0
2026-03-13 00:00:00-04:00,255.479996,256.329987,249.520004,250.119995,36930000,0.0,0.0
2026-03-16 00:00:00-04:00,252.110001,253.889999,249.880005,252.820007,32074200,0.0,0.0
2026-03-17 00:00:00-04:00,252.960007,255.130005,252.179993,254.229996,32361600,0.0,0.0
2026-03-18 00:00:00-04:00,252.625000,254.940002,249.000000,249.940002,34652568,0.0,0.0